id = "0009"
title = "Is Building a Gaming PC Still Worth It?"
date = 2026-01-27
author = "3G Hugo Leung"
tags = [
    "Technology Guide",
    "Computing",
    "PC"
]
draft = false
thumbnail = "gaming_pc.png"
