id = "0004"
title = "Guide to Basic Computer Components"
date = 2024-11-26
author = "2B Ethan Mak"
tags = [
    "Technology Guide",
    "Computer Hardware",
    "Data Storage",
    "Gaming"
]
draft = false
thumbnail = "computercomponents.png"
