id = "0005"
title = "Quick read: What are "bugs" in computing?"
date = 2024-12-02
author = "3A Adrian Ma"
tags = [
    "Bug",
    "Errors",
    "Technology Guide",
    "Computer Software",
    "History",
]
draft = false
thumbnail = "bugpic3.jpg"
