id = "0002"
title = "Things you did not learn in CL lessons"
date = 2024-11-12
tags = [
    "Scratch",
    "App Inventor",
    "Python",
    "Computer Literacy",
]
draft = false
thumbnail = "normalmouse.png"
