id = "0003"
title = "The Evolution of Personal Computers and Laptops"
date = 2024-11-25
author = "3A Brandon Kwok"
tags = [
    "The Internet",
    "History",
    "Technology Guide",
    "Computer Hardware"
]
draft = false
thumbnail = "osborne1.jpg"
