id = "0001"
title = "Things you did not learn in CL lessons"
date = 2024-11-28
author = "3D Isaac Cheung"
tags = [
    "Scratch",
    "App Inventor",
    "Python",
    "Programming",
    "Tips and Tricks",
]
draft = false
thumbnail = "logo.jpg"
